"""loan details rate periods overpayments

Revision ID: 0b497fbd3481
Revises: a1b2c3d4e5f6
Create Date: 2026-09-16 12:14:34.062689

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b497fbd3481'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_details',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('secured_on_account_id', sa.Integer(), nullable=True),
    sa.Column('lender', sa.String(), nullable=True),
    sa.Column('original_amount_gbp', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('repayment_type', sa.Enum('repayment', 'interest_only', name='repaymenttype'), server_default='repayment', nullable=False),
    sa.Column('payment_day', sa.Integer(), server_default='1', nullable=False),
    sa.Column('overpayment_effect', sa.Enum('reduce_term', 'reduce_payment', name='overpaymenteffect'), server_default='reduce_term', nullable=False),
    sa.Column('overpayment_allowance_rate', sa.Float(), server_default='0.10', nullable=False),
    sa.Column('fallback_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secured_on_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('loan_overpayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_gbp', sa.Float(), nullable=False),
    sa.Column('is_planned', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_rate_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('annual_rate', sa.Float(), nullable=False),
    sa.Column('rate_type', sa.Enum('fixed', 'tracker', 'variable', 'svr', name='ratetype'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('payment_override_gbp', sa.Float(), nullable=True),
    sa.Column('erc_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_rate_periods')
    op.drop_table('loan_overpayments')
    op.drop_table('loan_details')
    # ### end Alembic commands ###
