"""instruments prices fx transactions positions

Revision ID: 9590ae349902
Revises: c4084b49be6e
Create Date: 2026-09-15 21:41:22.627036

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9590ae349902'
down_revision: str | Sequence[str] | None = 'c4084b49be6e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gbp_per_unit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('currency', 'date')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('quote_type', sa.String(), nullable=True),
    sa.Column('quote_currency', sa.String(), nullable=False),
    sa.Column('asset_class', sa.Enum('equity', 'bond', 'multi_asset', 'property', 'commodity', 'cash', 'crypto', 'other', name='assetclass'), server_default='equity', nullable=False),
    sa.Column('price_source', sa.Enum('yahoo', 'manual', name='pricesource'), nullable=False),
    sa.Column('manual_price_gbp', sa.Float(), nullable=True),
    sa.Column('manual_price_date', sa.Date(), nullable=True),
    sa.Column('last_price_native', sa.Float(), nullable=True),
    sa.Column('last_price_gbp', sa.Float(), nullable=True),
    sa.Column('prev_close_gbp', sa.Float(), nullable=True),
    sa.Column('last_price_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetch_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('instrument_prices',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_native', sa.Float(), nullable=False),
    sa.Column('close_gbp', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('yahoo', 'manual', name='pricesource'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'date')
    )
    op.create_table('positions',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('cost_basis_gbp', sa.Float(), nullable=False),
    sa.Column('realised_gain_gbp', sa.Float(), server_default='0', nullable=False),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'instrument_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('OPENING_BALANCE', 'BUY', 'SELL', 'DEPOSIT', 'WITHDRAWAL', 'DIVIDEND', 'INTEREST', 'FEE', 'TAX', 'TRANSFER_IN', 'TRANSFER_OUT', 'SPLIT', 'ADJUSTMENT', name='txntype'), nullable=False),
    sa.Column('units', sa.Float(), server_default='0', nullable=False),
    sa.Column('price_native', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), server_default='GBP', nullable=False),
    sa.Column('fx_gbp_per_unit', sa.Float(), server_default='1', nullable=False),
    sa.Column('amount_gbp', sa.Float(), nullable=False),
    sa.Column('fees_gbp', sa.Float(), server_default='0', nullable=False),
    sa.Column('cost_basis_gbp', sa.Float(), server_default='0', nullable=False),
    sa.Column('split_ratio', sa.Float(), nullable=True),
    sa.Column('contribution_source', sa.Enum('personal', 'employer', 'salary_sacrifice', 'tax_relief', 'government_bonus', 'transfer', name='contributionsource'), nullable=True),
    sa.Column('status', sa.Enum('confirmed', 'pending', name='txnstatus'), server_default='confirmed', nullable=False),
    sa.Column('source', sa.Enum('manual', 'opening', 'recurring', 'import', name='txnsource'), server_default='manual', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_date', ['account_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_account_date')

    op.drop_table('transactions')
    op.drop_table('positions')
    op.drop_table('instrument_prices')
    op.drop_table('instruments')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
