"""people accounts balances growth property settings tax_year_rules

Revision ID: c4084b49be6e
Revises: 38f2e12bc200
Create Date: 2026-09-15 21:06:44.482971

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4084b49be6e'
down_revision: str | Sequence[str] | None = '38f2e12bc200'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('investment', 'pension', 'cash', 'property', 'mortgage', 'loan', 'credit_card', 'other_asset', 'other_liability', name='category'), nullable=False),
    sa.Column('wrapper', sa.Enum('none', 'isa', 'lisa', 'jisa', 'gia', 'sipp', 'workplace_pension', 'db_pension', name='wrapper'), server_default='none', nullable=False),
    sa.Column('valuation_method', sa.Enum('holdings', 'balance', 'model', 'amortising', name='valuationmethod'), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('include_in_networth', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_liquid', sa.Boolean(), nullable=False),
    sa.Column('expected_return_rate', sa.Float(), nullable=True),
    sa.Column('annual_fee_rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('cash_balance_gbp', sa.Float(), server_default='0', nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('retirement_age', sa.Integer(), server_default='67', nullable=False),
    sa.Column('include_in_household', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tax_year_rules',
    sa.Column('tax_year_start', sa.Integer(), nullable=False),
    sa.Column('isa_allowance_gbp', sa.Float(), nullable=False),
    sa.Column('lisa_allowance_gbp', sa.Float(), nullable=False),
    sa.Column('jisa_allowance_gbp', sa.Float(), nullable=False),
    sa.Column('cash_isa_limit_gbp', sa.Float(), nullable=True),
    sa.Column('pension_annual_allowance_gbp', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tax_year_start')
    )
    op.create_table('account_owners',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('share', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'person_id')
    )
    op.create_table('balance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance_gbp', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'statement', 'valuation', 'csv', 'estimate', name='balancesource'), server_default='manual', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_balance_entries_account_date')
    )
    op.create_table('growth_models',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('annual_rate', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('compound', 'linear', name='growthmethod'), server_default='compound', nullable=False),
    sa.Column('floor_value_gbp', sa.Float(), nullable=True),
    sa.Column('cap_value_gbp', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('property_details',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price_gbp', sa.Float(), nullable=True),
    sa.Column('is_main_residence', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_details')
    op.drop_table('growth_models')
    op.drop_table('balance_entries')
    op.drop_table('account_owners')
    op.drop_table('tax_year_rules')
    op.drop_table('settings')
    op.drop_table('people')
    op.drop_table('accounts')
    # ### end Alembic commands ###
